### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'initializeJSI' of null, js engine: hermes

### ISSUE THREAD

**Issue by taraktikos** [morrowdigital/watermelondb-plugin-example#4]
Cloned repository without any changes and started on ios simulator (IPhone 15)
MacOS M1

<img width="349" alt="image" src="https://github.com/morrowdigital/watermelondb-plugin-example/assets/1644814/1767b491-6d49-49c0-8e0a-e80e56cf2f05">

**Comment by killerchip** [comment]
@taraktikos Did you manage to solve this?

**Comment by madsrode** [comment]
@killerchip In case you or someone else should still experience this, maybe this can help.
Make sure to use expo run:android instead of expo start.
Expo Go can't be used with native code and it is mentioned on the readme as "Then rebuild your app as described in the ["Adding custom native code"](https://docs.expo.io/workflow/customizing/) guide.".

**Comment by killerchip** [comment]
@madsrode 

> @killerchip In case you or someone else should still experience this, maybe this can help. Make sure to use expo run:android instead of expo start. Expo Go can't be used with native code and it is mentioned on the readme as "Then rebuild your app as described in the ["Adding custom native code"](https://docs.expo.io/workflow/customizing/) guide.".

Thanks for mentioning. We have updated the README
